# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/SipClient
CFG_INC=-IBasicUsageEnvironment/include -Iinclude -IliveMedia/include \
	-Igroupsock/include -IUsageEnvironment/include \
	-Ipjproject-2.4.5/pjsip/include -Ipjproject-2.4.5/pjlib/include \
	-Ipjproject-2.4.5/pjlib-util/include \
	-Ipjproject-2.4.5/pjmedia/include -Ipjproject-2.4.5/pjnath/include 
CFG_LIB=-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjsip/lib/ \
	-lpjsua-x86_64-unknown-linux-gnu -lpjsip-x86_64-unknown-linux-gnu \
	-lpjsip-ua-x86_64-unknown-linux-gnu \
	-lpjsip-simple-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjmedia/lib/ \
	-lpjmedia-codec-x86_64-unknown-linux-gnu \
	-lpjmedia-audiodev-x86_64-unknown-linux-gnu \
	-lpjmedia-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib/lib/ \
	-lpj-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjnath/lib/ \
	-lpjnath-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib-util/lib/ \
	-lpjlib-util-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/all/ \
	-lthirdParty \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/gsm/lib/ \
	-lgsm -lpthread -lm 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/main.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/main.o \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjsip/lib/ \
	-lpjsua-x86_64-unknown-linux-gnu -lpjsip-x86_64-unknown-linux-gnu \
	-lpjsip-ua-x86_64-unknown-linux-gnu \
	-lpjsip-simple-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjmedia/lib/ \
	-lpjmedia-codec-x86_64-unknown-linux-gnu \
	-lpjmedia-audiodev-x86_64-unknown-linux-gnu \
	-lpjmedia-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib/lib/ \
	-lpj-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjnath/lib/ \
	-lpjnath-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib-util/lib/ \
	-lpjlib-util-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/all/ \
	-lthirdParty \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/gsm/lib/ \
	-lgsm -lpthread -lm 

COMPILE=gcc -c   -g -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=gcc  -g -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/SipClient
CFG_INC=-IBasicUsageEnvironment/include -Iinclude -IliveMedia/include \
	-Igroupsock/include -IUsageEnvironment/include \
	-Ipjproject-2.4.5/pjsip/include -Ipjproject-2.4.5/pjlib/include \
	-Ipjproject-2.4.5/pjlib-util/include \
	-Ipjproject-2.4.5/pjmedia/include -Ipjproject-2.4.5/pjnath/include 
CFG_LIB=-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjsip/lib/ \
	-lpjsua-x86_64-unknown-linux-gnu -lpjsip-x86_64-unknown-linux-gnu \
	-lpjsip-ua-x86_64-unknown-linux-gnu \
	-lpjsip-simple-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjmedia/lib/ \
	-lpjmedia-codec-x86_64-unknown-linux-gnu \
	-lpjmedia-audiodev-x86_64-unknown-linux-gnu \
	-lpjmedia-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib/lib/ \
	-lpj-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjnath/lib/ \
	-lpjnath-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib-util/lib/ \
	-lpjlib-util-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/all/ \
	-lthirdParty \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/gsm/lib/ \
	-lgsm -lpthread -lm 
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/main.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/main.o \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjsip/lib/ \
	-lpjsua-x86_64-unknown-linux-gnu -lpjsip-x86_64-unknown-linux-gnu \
	-lpjsip-ua-x86_64-unknown-linux-gnu \
	-lpjsip-simple-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjmedia/lib/ \
	-lpjmedia-codec-x86_64-unknown-linux-gnu \
	-lpjmedia-audiodev-x86_64-unknown-linux-gnu \
	-lpjmedia-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib/lib/ \
	-lpj-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjnath/lib/ \
	-lpjnath-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/pjlib-util/lib/ \
	-lpjlib-util-x86_64-unknown-linux-gnu \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/all/ \
	-lthirdParty \
	-L/home/andyaoe/Projects/SipClient/pjproject-2.4.5/third_party/gsm/lib/ \
	-lgsm -lpthread -lm 

COMPILE=gcc -c   -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=gcc  -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
